package et.safaricom.transaction.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Min;
import org.hibernate.validator.constraints.URL;

/**
 * Request body for making a pay-out request.
 */
@Data
@Builder
public class PayOutRequest {

    /**
     * Unique identifier for the transaction request.
     * Type: String
     */
    @JsonProperty("OriginatorConversationID")
    @NotNull(message = "OriginatorConversationID cannot be null")
    @Size(min = 1, message = "OriginatorConversationID must not be empty")
    private String originatorConversationID;

    /**
     * This is an API user created by the Business Administrator of the M-PESA disbursement account.
     * It is used to initiate authorized B2C transactions through the API.
     * Type: String
     * Example: init_B2C
     */
    @JsonProperty("InitiatorName")
    @NotNull(message = "InitiatorName cannot be null")
    private String initiatorName;

    /**
     * This value is generated by encrypting the API initiator password.
     * In the sandbox environment, the password is provisioned within the simulator.
     * In production, it is created during user registration on the M-PESA organization portal.
     * Type: Alpha-numeric
     * Example: 32SzVdmCvjpmQfw3X2RK8UAv7xuhh304dXxFC5+3lslkk2TDJY/Lh6ESVwtqMxJzF7qA==
     */
    @JsonProperty("SecurityCredential")
    @NotNull(message = "SecurityCredential cannot be null")
    @Size(min = 1, message = "SecurityCredential must not be empty")
    private String securityCredential;

    /**
     * Any additional information to be associated with the transaction.
     * Type: Alpha-numeric
     * Example: Sequence of characters up to 100
     */
    @JsonProperty("Occassion")
    @Size(max = 100, message = "Occassion must be up to 100 characters")
    private String occassion;

    /**
     * This command defines the B2C transaction type.
     * Type: Alphanumeric
     * Example: SalaryPayment, BusinessPayment, PromotionPayment
     */
    @JsonProperty("CommandID")
    @NotNull(message = "CommandID cannot be null")
    @Size(min = 1, message = "CommandID must not be empty")
    private String commandID;

    /**
     * The Business organization's shortcode from which the money is sent.
     * Type: Number
     * Example: Shortcode (5-6 digits) e.g. 123454
     */
    @JsonProperty("PartyA")
    @NotNull(message = "PartyA cannot be null")
    @Pattern(regexp = "\\d{5,6}", message = "PartyA must be a 5-6 digit number")
    private String partyA;

    /**
     * The customer mobile number to receive the amount.
     * Type: Phone number
     * Example: 2517100100
     */
    @JsonProperty("PartyB")
    @NotNull(message = "PartyB cannot be null")
    @Pattern(regexp = "\\d+", message = "PartyB must be a valid phone number")
    private String partyB;

    /**
     * Any additional information to be associated with the transaction.
     * Type: String
     * Example: Sentence of up to 100 characters.
     */
    @JsonProperty("Remarks")
    @Size(max = 100, message = "Remarks must be up to 100 characters")
    private String remarks;

    /**
     * The amount of money being sent to the customer.
     * Type: Number
     * Example: 30671
     */
    @JsonProperty("Amount")
    @NotNull(message = "Amount cannot be null")
    @Min(value = 1, message = "Amount must be greater than 0")
    private int amount;

    /**
     * This is the URL to be specified in your request that will be used by API Proxy
     * to send notification in case the payment request is timed out while awaiting processing in the queue.
     * Type: URL
     * Example: https://ip or domain:port/path
     */
    @JsonProperty("QueueTimeOutURL")
    @NotNull(message = "QueueTimeOutURL cannot be null")
    @URL(message = "QueueTimeOutURL must be a valid URL")
    private String queueTimeOutURL;

    /**
     * This is the URL to be specified in your request that will be used by M-PESA
     * to send notification upon processing of the payment request.
     * Type: URL
     * Example: https://ip or domain:port/path
     */
    @JsonProperty("ResultURL")
    @NotNull(message = "ResultURL cannot be null")
    @URL(message = "ResultURL must be a valid URL")
    private String resultURL;
}
